"""Tests for the golden-file fixture loader.

Tests that require golden files (generated by scripts/generate_golden.R) are
skipped automatically when those files are not present, so the suite stays
green in CI without R.
"""

from __future__ import annotations

import importlib
from pathlib import Path

import pytest

GOLDEN_PRESENT = Path("tests/golden/GlobalPatterns/otu_table.parquet").exists()

skip_no_golden = pytest.mark.skipif(
    not GOLDEN_PRESENT,
    reason="golden files not generated — run `Rscript scripts/generate_golden.R`",
)


# ---- import sanity (always runs) -------------------------------------------


def test_testing_module_importable() -> None:
    mod = importlib.import_module("pyloseq.testing")
    for name in [
        "load_global_patterns_reference",
        "load_enterotype_reference",
        "load_esophagus_reference",
        "load_soilrep_reference",
        "load_golden",
    ]:
        assert hasattr(mod, name), f"pyloseq.testing missing: {name}"


def test_load_missing_dataset_raises() -> None:
    from pyloseq.testing.fixtures import _load_dataset

    with pytest.raises(FileNotFoundError):
        _load_dataset("nonexistent_dataset_xyz")


# ---- golden-file tests (skip when files absent) ----------------------------


@skip_no_golden
def test_global_patterns_loads(benchmark: pytest.FixtureRequest) -> None:
    from pyloseq.testing import load_global_patterns_reference

    result = benchmark(load_global_patterns_reference)
    assert "otu_table" in result
    assert "taxa_sums" in result
    assert "sample_sums" in result


@skip_no_golden
def test_global_patterns_otu_table_shape() -> None:
    from pyloseq.testing import load_global_patterns_reference

    ref = load_global_patterns_reference()
    # GlobalPatterns: 19216 taxa × 26 samples
    otu = ref["otu_table"]
    assert otu.shape == (19216, 26) or otu.shape == (26, 19216), (
        f"Unexpected OTU table shape: {otu.shape}"
    )


@skip_no_golden
def test_global_patterns_tax_table_shape() -> None:
    from pyloseq.testing import load_global_patterns_reference

    ref = load_global_patterns_reference()
    assert ref["tax_table"].shape == (19216, 7)


@skip_no_golden
def test_enterotype_sample_data_shape() -> None:
    from pyloseq.testing import load_enterotype_reference

    ref = load_enterotype_reference()
    # enterotype: 280 samples × 9 variables
    assert ref["sample_data"].shape == (280, 9)


@skip_no_golden
def test_esophagus_has_tree() -> None:
    from pyloseq.testing import load_esophagus_reference

    ref = load_esophagus_reference()
    assert "phy_tree_newick" in ref
    assert len(ref["phy_tree_newick"]) > 10


@skip_no_golden
def test_taxa_sums_is_series() -> None:
    import pandas as pd

    from pyloseq.testing import load_global_patterns_reference

    ref = load_global_patterns_reference()
    assert isinstance(ref["taxa_sums"], pd.Series)
    assert len(ref["taxa_sums"]) == 19216


@skip_no_golden
def test_load_golden_estimate_richness() -> None:
    from pyloseq.testing.fixtures import load_golden

    df = load_golden("GlobalPatterns", "estimate_richness")
    assert "Observed" in df.columns or "Shannon" in df.columns


@skip_no_golden
def test_provenance_readable() -> None:
    from pyloseq.testing.fixtures import golden_provenance

    prov = golden_provenance()
    assert "phyloseq" in prov
    assert "R" in prov
    assert "generated_at" in prov
